config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", change_password: "registrations" }

  root 'products#index'

  namespace :account do
    resources :orders
    resources :posts
    resources :comments
    resources :users do
      member do
        get :change_password
      end
    end

  end

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    resources :comments
    resources :posts do
      member do
        post :like
        post :unlike
        post :star
        post :unstar
      end
    end
    member do
      post :add_to_cart
      post "rate" => "products#rate"
    end
  end

  resources :posts do
    resources :comments do
      member do
        post :like
        post :unlike
      end
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

  resources :cart_items

end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  before_validation :generate_friendly_id, :on => :create
  mount_uploader :image, ImageUploader

  has_many :cart_items
  has_many :comments, as: :commentable
  has_many :posts
  has_many :scores, :class_name => "ProductScore"

  def find_score(user)
    user && self.scores.where( :user_id => user.id ).first
  end

  def average_score
    self.scores.average(:score)
  end

  def to_param
    self.friendly_id
  end

  protected

  def generate_friendly_id
    self.friendly_id ||= SecureRandom.uuid
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  before_action :find_product, only: [:edit, :update, :destroy]

  layout "admin"

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: "成功添加了新商品！"
    end
  end

  def edit
  end

  def update
    @product.update(product_params)
    redirect_to admin_products_path, notice: "商品信息已更新！"
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path, alert: "成功删除了一件商品！"
  end

private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image)
  end

  def find_product
    @product = Product.find_by_friendly_id!(params[:id])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :add_to_cart, :rate]

  def index
    @products = Product.all
  end

  def show
    @posts = @product.posts.order( "id DESC" ).limit(5)

    if params[:max_id]
      @posts = @posts.where( "id < ?", params[:max_id] )
    end

    respond_to do |format|
      format.html
      format.js
    end

    @comments = @product.comments.order("id DESC").all
  end

  def add_to_cart
    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "你已成功将 #{@product.title} 加入购物车"
    else
      flash[:warning] = "你的购物车内已有此物"
    end
  end


  def rate
    existing_score = @product.find_score(current_user)
    if existing_score
      existing_score.update( :score => params[:score] )
    else
      @product.scores.create( :score => params[:score], :user => current_user )
    end

    render :json => { :average_score => @product.average_score }
  end


  private

  def find_product
    @product = Product.find_by_friendly_id!(params[:id])
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product] do |f| %>
  <div class="group">
    <%= f.input :title, label: "商品名称" %>
  </div>

  <div class="group">
    <%= f.input :description, label: "商品描述" %>
  </div>

  <div class="group">
    <%= f.input :quantity, label: "商品库存" %>
  </div>

  <div class="group">
    <%= f.input :price, label: "商品价格" %>
  </div>

  <% if @product.image.present? %>
    <span>目前商品图</span>
    <br>
    <%= image_tag(@product.image.thumb.url) %>
  <% end %>

  <div class="group">
    <%= f.input :image, as: :file, label: "上传商品图片" %>
  </div>

  <%= f.submit "Submit", class:"btn btn-default", :disable_with => 'Submiting...' %>
<% end %>

app/views/admin/products/edit.html.erb
<h1>编辑新商品</h1>

<%= render :partial => "form" %>

app/views/admin/products/index.html.erb
  <h1>Product List</h1>

  <%= link_to("Add new Prodcut", new_admin_product_path, class: "btn btn-default pull-right") %>
  <br>
  <table class="table grid">
    <thead>
      <tr>
        <th>#</th>
        <th width='220'>商品图片</th>
        <th>商品名称</th>
        <th>商品描述</th>
        <th>库存</th>
        <th>价格</th>
        <th>选项</th>
        <th>创建日期</th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td>
          <%= link_to product_path(product) do %>
            <% if product.image.present? %>
              <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
            <% else %>
              <%= image_tag("http://placehold,it/200x200&text=No Pic", class: "thumbnail") %>
            <% end %>
          <% end %>
        </td>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.quantity %></td>
        <td><%= product.price %></td>
        <td><%= link_to("edit", edit_admin_product_path(product), class:   "btn btn-warning btn-sm") %> | <%= link_to("delete", admin_product_path(product), method: :delete,  class:   "btn btn-danger btn-sm") %></td>
        <td><%= product.created_at.to_s(:short) %></td>
      </tr>

      <% end %>
    </tbody>
  </table>

app/views/admin/products/new.html.erb
<h1>增加新商品</h1>

<%= render :partial => "form" %>