config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", change_password: "registrations" }

  root 'products#index'

  namespace :account do
    resources :orders
    resources :posts
    resources :comments
    resources :users do
      member do
        get :change_password
      end
    end

  end

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    resources :comments
    resources :posts do
      member do
        post :like
        post :unlike
        post :star
        post :unstar
      end
    end
    member do
      post :add_to_cart
      post "rate" => "products#rate"
    end
  end

  resources :posts do
    resources :comments do
      member do
        post :like
        post :unlike
      end
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

  resources :cart_items

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  belongs_to :product, counter_cache: true
  belongs_to :user, counter_cache: true
  has_many :comments, dependent: :destroy, as: :commentable

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :like, :unlike, :star, :unstar, :destroy]
  before_action :find_product, only: [:new, :create, :destroy, :edit, :update, :like, :unlike, :star, :unstar]
  before_action :find_post, only: [:edit, :destroy, :update, :like, :unlike, :star, :unstar]

  def new
    @post = @product.posts.new
  end

  def create
    @post = @product.posts.new(post_params)
    @post.user = current_user
    @post.save
  end

  def show
    @post = Post.find(params[:id])
    @product = @post.product
    @comments = @post.comments.all.order("id DESC")
    @comment = @post.comments.new
  end

  def edit
  end

  def update
    @post.update(post_params)
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
  end

  def like
    current_user.create_action(:like, target: @post)
  end

  def unlike
    current_user.destroy_action(:like, target: @post)
    render "like"
  end

  def star
    current_user.create_action(:star, target: @post)
  end

  def unstar
    current_user.destroy_action(:star, target: @post)
    render "star"
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def find_product
    @product = Product.find_by_friendly_id!(params[:product_id])
  end

  def find_post
    @post = @product.posts.find(params[:id])
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def render_post_content(content)
    sanitize(content)
  end

end

app/views/posts/_post_edit.html.erb
<div id="post-<%= post.id %>">
  <%= simple_form_for [@product, @post], remote: true do |f| %>
    <div class="form-group">
      <%= f.input :title, label: "题目", input_html: { class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.input :content, label: "内容", input_html: { class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.submit "更新评测", method: :patch,  disable_with: "Submiting...", class: "btn btn-default"%>
    </div>
  <% end %>
</div>

app/views/posts/_post_item.html.erb
<div id="post-<%= post.id %>" class="panel panel-default">
  <div class="panel-heading">
    <img src=" <%= render_user_avatar(post.user, 20) %> " alt="avatar" >
    <b>
      <%= post.user.display_name %> 对商品 「<%= link_to(@product.title, product_path(@product)) %>」 发表了评测《 <%= post.title %>》,
    <span><%= post.created_at.to_s(:short) %></span>
    <% if current_user && current_user == post.user %>
      <%= link_to edit_product_post_path(post.product, post), class: "btn btn-warning btn-xs pull-right", style: "margin-left:0.25em;margin-right:0.25em;", remote: true do %>
        <i class="fa fa-edit"></i>
      <% end %>

      <%= link_to post_path(post), method: :delete, data: { confirm: "您确定要删除该文章吗？" }, class: "btn btn-danger btn-xs pull-right", style: "margin-left:0.25em;margin-right:0.25em;", remote: true do %>
        <i class="fa fa-trash"></i>
      <% end %>
    <% end %>
  </div>

  <div class="panel-body">
    <span id="post-thumbsup-<%= post.id %>" class="label label-success"> <%= post.likes_count %> <i class="fa fa-thumbs-up"></i></span>

    <span id="post-heart-<%= post.id %>" class="label label-success"> <%= post.stars_count %> <i class="fa fa-heart"></i></span>

    <%= render_post_content(post.content) %>

    <%= link_to("评论", post_path(post), class: "btn btn-primary btn-xs pull-right", style: "margin-left:0.5em;margin-right:0.5em;" ) %>

    <%= render :partial => "posts/post_like", locals: { :post => post } %>
    <%= render :partial => "posts/post_star", locals: { :post => post } %>



  </div>
</div>

app/views/posts/_post_like.html.erb
<div id="post-like-<%= post.id %>">
  <% if current_user %>
    <% if current_user.find_action(:like, target: post).present? %>
      <%= link_to unlike_product_post_path(@product, post), method: :post, remote: true, class: "btn btn-default btn-xs pull-right", style: "margin-left:0.25em;margin-right:0.25em;" do %>
        <i class="fa fa-thumbs-up" aria-hidden="true"></i>
      <% end %>
    <% else %>
      <%= link_to like_product_post_path(@product, post), method: :post, remote: true, class: "btn btn-default btn-xs pull-right", style: "margin-left:0.25em;margin-right:0.25em;" do %>
        <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/posts/_post_new.html.erb
<div id="add-post">
  <%= simple_form_for [@product, @post], remote: true do |f| %>
    <div class="form-group">
      <%= f.input :title, label: "题目", input_html: { class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.input :content, label: "内容",  as: :ckeditor %>
    </div>
    <div class="form-group">
      <%= f.submit "发布评测", disable_with: "Submiting...", class: "btn btn-default"%>
      <hr>
    </div>
  <% end %>
</div>

app/views/posts/_post_star.html.erb
<div id="post-star-<%= post.id %>">
  <% if current_user %>
    <% if current_user.find_action(:star, target: post).present? %>
      <%= link_to unstar_product_post_path(@product, post), method: :post, remote: true, class: "btn btn-default btn-xs pull-right", style: "margin-left:0.25em;margin-right:0.25em;" do %>
        <i class="fa fa-heart" aria-hidden="true"></i>
      <% end %>
    <% else %>
      <%= link_to star_product_post_path(@product, post), method: :post, remote: true, class: "btn btn-default btn-xs pull-right", style: "margin-left:0.25em;margin-right:0.25em;" do %>
        <i class="fa fa-heart-o" aria-hidden="true"></i>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/posts/create.js.erb
<% if @post.valid? %>
  $("#post-list").prepend("<%=j render :partial => "post_item", :locals => { :post => @post } %>");
  $("#add-post").replaceWith("<%=j link_to "新增评测", new_product_post_path(@product), class: "btn btn-success", id: "add-post", remote: true %><hr>");
  $("#post_title").val("");
  $("#post_content").val("");
<% else %>
  alert("发表评测失败")
<% end %>

app/views/posts/destroy.js.erb
$("#post-<%= @post.id %>").remove();

app/views/posts/edit.js.erb
$("#post-<%= @post.id %>").replaceWith("<%=j render :partial => "post_edit", :locals => { :product => @product, :post => @post } %>")

app/views/posts/like.js.erb
str = "<%=j render :partial => "posts/post_like", :locals => { :post => @post } %>";
$("#post-like-<%= @post.id %>").html(str);
$("#post-thumbsup-<%= @post.id %>").html('<%= @post.like_by_user_actions.count %> <i class="fa fa-thumbs-up"></i>');

app/views/posts/new.js.erb
$("#add-post").replaceWith("<%=j render :partial => "post_new", :locals => { :product => @product, :post => @post } %>")

app/views/posts/show.html.erb
<%= render :partial => "post_item", :locals => { :post => @post} %>


<% if current_user %>
  <div>
    <%= simple_form_for [@post, @comment], remote: true do |f| %>
      <div class="form-group">
        <%= f.input :content, label: "发表评论", input_html: { class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
      </div>
    <% end %>
  </div>
<% else %>
  <%= link_to "登录后添加评测", new_user_session_path , class: "btn btn-primary" %>
<% end %>
<hr>

<div id="comment-list">
  <% if @comments.present? %>
    <% @comments.each do |comment| %>
      <%= render :partial => "/comments/comment_item", :locals => {:comment => comment} %>
    <% end %>
  <% else %>
    还有没有评论，赶紧抢沙发。
  <% end %>
</div>

app/views/posts/star.js.erb
str = "<%=j render :partial => "posts/post_star", :locals => { :post => @post } %>";
$("#post-star-<%= @post.id %>").html(str);
$("#post-heart-<%= @post.id %>").html('<%= @post.star_by_user_actions.count %> <i class="fa fa-heart"></i>');

app/views/posts/update.js.erb
<% if @post.valid? %>
  $("#post-<%= @post.id %>").replaceWith("<%=j render :partial => "post_item", :locals => { :post => @post } %>")
  // $("#post_title").val("");
  // $("#post_content").val("");
<% else %>
  alert("发表评测失败")
<% end %>