config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", change_password: "registrations" }

  root 'products#index'

  namespace :account do
    resources :orders
    resources :posts
    resources :comments
    resources :users do
      member do
        get :change_password
      end
    end

  end

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    resources :comments
    resources :posts do
      member do
        post :like
        post :unlike
        post :star
        post :unstar
      end
    end
    member do
      post :add_to_cart
      post "rate" => "products#rate"
    end
  end

  resources :posts do
    resources :comments do
      member do
        post :like
        post :unlike
      end
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

  resources :cart_items

end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  before_validation :generate_friendly_id, :on => :create
  mount_uploader :image, ImageUploader

  has_many :cart_items
  has_many :comments, as: :commentable
  has_many :posts
  has_many :scores, :class_name => "ProductScore"

  def find_score(user)
    user && self.scores.where( :user_id => user.id ).first
  end

  def average_score
    self.scores.average(:score)
  end

  def to_param
    self.friendly_id
  end

  protected

  def generate_friendly_id
    self.friendly_id ||= SecureRandom.uuid
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  before_action :find_product, only: [:edit, :update, :destroy]

  layout "admin"

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: "成功添加了新商品！"
    end
  end

  def edit
  end

  def update
    @product.update(product_params)
    redirect_to admin_products_path, notice: "商品信息已更新！"
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path, alert: "成功删除了一件商品！"
  end

private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image)
  end

  def find_product
    @product = Product.find_by_friendly_id!(params[:id])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :add_to_cart, :rate]

  def index
    @products = Product.all
  end

  def show
    @posts = @product.posts.order( "id DESC" ).limit(5)

    if params[:max_id]
      @posts = @posts.where( "id < ?", params[:max_id] )
    end

    respond_to do |format|
      format.html
      format.js
    end

    @comments = @product.comments.order("id DESC").all
  end

  def add_to_cart
    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "你已成功将 #{@product.title} 加入购物车"
    else
      flash[:warning] = "你的购物车内已有此物"
    end
  end


  def rate
    existing_score = @product.find_score(current_user)
    if existing_score
      existing_score.update( :score => params[:score] )
    else
      @product.scores.create( :score => params[:score], :user => current_user )
    end

    render :json => { :average_score => @product.average_score }
  end


  private

  def find_product
    @product = Product.find_by_friendly_id!(params[:id])
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/add_to_cart.js.erb
$("#cart-number").html('<span id="cart-number"> <%= current_cart.products.count %></span>');
$("#flash-show").prepend('<%=j render :partial => "common/flashes" %>');

app/views/products/index.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-xs-6 col-md-3">
      <%= link_to product_path(product) do %>
        <% if product.image.present? %>
          <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
        <% else %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
        <% end %>
      <% end %>
      <%= product.title %> ￥ <%= product.price %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <% if @product.image.present? %>
      <%= image_tag(@product.image.medium.url, class: "thumbnail") %>
    <% else %>
      <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
    <% end %>
  </div>
  <div class="col-md-6 panel-body">
    <h2> <%= @product.title %> </h2>

    <span class="average-score"><%= @product.average_score %></span>
    <div class="raty" data-score="<%= @product.find_score(current_user).try(:score) || 0 %>" data-score-url="<%= rate_product_path(@product) %>"></div>

    <div style="height:100px;">
      <p>
        <%= @product.description %>
      </p>
    </div>
    <div> <%= t("quantity") %> : <%= @product.quantity %> </div>
    <div class="product-price"> ￥ <%= @product.price %> </div>
    <div class="pull-right">
      <% if @product.quantity.present? && @product.quantity > 0 %>
        <%= link_to(t("add_to_cart"), add_to_cart_product_path(@product), method: :post, class: "btn btn-lg btn-danger", remote: true) %>
      <% else %>
        已经销售一空，无法购买
      <% end %>
    </div>
  </div>
</div>



<% if current_user %>
  <div id="add-post">
    <%= link_to "新增评测", new_product_post_path(@product), class: "btn btn-success",  remote: true %>
  </div>
<% else %>
  <%= link_to "登录后添加评测", new_user_session_path , class: "btn btn-success" %>
<% end %>

<hr>

<div id="post-list">
  <% if @posts.present? %>
    <% @posts.each do |post| %>
      <%= render :partial => "posts/post_item", locals: { :post => post }%>
    <% end %>
  <% else %>
    <p>暂无评测，快来添加吧
      <%= link_to new_product_post_path(@product) do %>
        <i class="fa fa-edit"></i>
      <% end %>
    </p>
  <% end %>
</div>


<script>
  $(".raty").raty({
   path: '/images/',
   score: function() { return $(this).data('score'); },
   click: function(score) {
     var that = this;
     $.ajax({
       url: $(this).data("score-url"),
       method: "POST",
       data: { score: score },
       dataType: "json",
       success: function(data){
         $(that).closest(".panel-body").find(".average-score").html( data["average_score"] );
       }
     })
   }
  });


  // 记下目前画面最小的贴文 ID
  var current_post_id = <%= @posts.last.id %>;
  var product_id = <%= @product.id %>

  // 当捲轴动的时候，会触发这个事件
  $(window).scroll(function(){
    // 当捲到最下面的时候
    if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
      var url = "/products/" + product_id + "?max_id=" + current_post_id;
      if (url) {
        $.ajax({
          method: "GET",
          url: url,
          dataType: "script"
        })
      } else {
        console.log("data ended")
      }
    }
  })
</script>

app/views/products/show.js.erb
<% @posts.each do |post| %>
  $("#post-list").append("<hr>")
  $("#post-list").append("<%=j render :partial => "posts/post_item", :locals => { :post => post } %>");
<% end %>

<% if @posts.any? %>
  var current_post_id = <%= @posts.last.id %>;
<% end %>